config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root to: 'pages#main'

  get 'tournaments/:id/stat', to: 'tournaments#stat', as: 'tournament_stat'
  ActiveAdmin.routes(self)
  authenticate :user, lambda { |u| u.role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :themes, only: [:index, :show]
  resources :profiles
  resources :levels, only: [:show, :index]
  resources :posts, only: [:show, :index]
  resources :tournaments, only: [:show]
  resources :games, only: [:index, :show] do
    # collection do
    #   get ':id/rank', to: 'games#rank', as: 'rank'
    #   get ':id/play', to: 'user_games#play', as: 'play'
    #   get ':id/results', to: 'user_games#results', as: 'results'
    #   post ':id/begin_stage', to: 'user_games#begin_stage', as: 'begin_stage'
    #   post ':id/finish_stage', to: 'user_games#finish_stage', as: 'finish_stage'
    #   post ':game_id/save_statistic_anwers', to: 'user_games#save_statistic_anwers', as: 'user_game/save_statistic_anwers'
    # end
  end
  resources :user_games, only: [:create, :destroy] do
    resources :user_answers, only: [:create]
  end

  get 'games/:id/rank', to: 'games#rank', as: 'game_rank'
  get 'games/:id/play', to: 'user_games#play', as: 'user_game/play'
  get 'games/:id/results', to: 'user_games#results', as: 'user_game/results'
  post 'games/:id/begin_stage', to: 'user_games#begin_stage', as: 'user_game/begin_stage'
  post 'games/:id/finish_stage', to: 'user_games#finish_stage', as: 'user_game/finish_stage'
  post 'games/:game_id/save_statistic_anwers', to: 'user_games#save_statistic_anwers', as: 'user_game/save_statistic_anwers'

  namespace :statistics do
    get 'best_display'
    get 'best_close'
    get 'worst_display'
    get 'worst_close'
    get 'game_display'
    get 'game_close'
    get 'post_display'
    get 'post_close'
    get 'count_display'
    get 'count_close'
  end

  get 'callbacks/facebook'
  get 'search', to: 'pages#search'
  get 'pages/:url', to: 'pages#show', as: 'page'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    authenticated :user do
      root to: 'admin/dashboard#index', as: :authenticated_root
    end
    unauthenticated :user do
      root to: 'users/sessions#new', as: :unauthenticated_root
    end
  end

end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController

  def best_display
    @questions = Question.sort_array_by_best
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Включите JavaScript" }
      format.js {}
    end
  end

  def best_close
    @questions = Question.sort_array_by_best[0..4]
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Включите JavaScript" }
      format.js {}
    end
  end

  def worst_display
    @questions = Question.sort_array_by_worst
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Включите JavaScript" }
      format.js {}
    end
  end

  def worst_close
    @questions = Question.sort_array_by_worst[0..4]
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Включите JavaScript" }
      format.js {}
    end
  end

  def game_display
    @games = Game.sort_array_by_rating
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Включите JavaScript" }
      format.js {}
    end
  end

  def game_close
    @games = Game.sort_array_by_rating[0..4]
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Включите JavaScript" }
      format.js {}
    end
  end

  def post_display
    @posts = Post.post_sort
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Включите JavaScript" }
      format.js {}
    end
  end

  def post_close
    @posts = Post.post_sort.first(5)
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Включите JavaScript" }
      format.js {}
    end
  end

  def count_display
    @games = Game.game_sort
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Включите JavaScript" }
      format.js {}
    end
  end

  def count_close
    @games = Game.game_sort[0..4]
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Включите JavaScript" }
      format.js {}
    end
  end

end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/statistics/best_close.js.erb
rating = $("#best");
rating.empty();
<% @questions.each do |question| %>
element = $('<li><%= question.body %> (<%= question.question_bests.count %>)</li>');
rating.append(element);
<% end %>
element = $('<li><%= link_to "Свернуть", statistics_best_display_path, remote: true %></li>');
rating.append(element);

app/views/statistics/best_display.js.erb
rating = $("#best");
rating.empty();
<% @questions.each do |question| %>
element = $('<li><%= question.body %> (<%= question.question_bests.count %>)</li>');
rating.append(element);
<% end %>
element = $('<li><%= link_to "Свернуть", statistics_best_close_path, remote: true %></li>');
rating.append(element);

app/views/statistics/count_close.js.erb
rating = $("#game");
rating.empty();
<% @games.each do |game| %>
element = $('<li><%= game.title %> (<%= game.user_games.count %>)</li>');
rating.append(element);
<% end %>
element = $('<li><%= link_to "Свернуть", statistics_count_display_path, remote: true %></li>');
rating.append(element);

app/views/statistics/count_display.js.erb
rating = $("#game");
rating.empty();
<% @games.each do |game| %>
element = $('<li><%= game.title %> (<%= game.user_games.count %>)</li>');
rating.append(element);
<% end %>
element = $('<li><%= link_to "Свернуть", statistics_count_close_path, remote: true %></li>');
rating.append(element);

app/views/statistics/game_close.js.erb
rating = $("#rating");
rating.empty();
<% @games.each do |game| %>
element = $('<li><%= game.title %> (<%= game.rating %>)</li>');
rating.append(element);
<% end %>
element = $('<li><%= link_to "Свернуть", statistics_game_display_path, remote: true %></li>');
rating.append(element);

app/views/statistics/game_display.js.erb
rating = $("#rating");
rating.empty();
<% @games.each do |game| %>
element = $('<li><%= game.title %> (<%= game.rating %>)</li>');
rating.append(element);
<% end %>
element = $('<li><%= link_to "Свернуть", statistics_game_close_path, remote: true %></li>');
rating.append(element);

app/views/statistics/post_close.js.erb
rating = $("#post");
rating.empty();
<% @posts.each do |post| %>
element = $('<li><%= post.title %> (<%= post.count %>)</li>');
rating.append(element);
<% end %>
element = $('<li><%= link_to "Отобразить остальное", statistics_post_display_path, remote: true %></li>');
rating.append(element);

app/views/statistics/post_display.js.erb
rating = $("#post");
rating.empty();
<% @posts.each do |post| %>
element = $('<li><%= post.title %> (<%= post.count %>)</li>');
rating.append(element);
<% end %>
element = $('<li><%= link_to "Свернуть", statistics_post_close_path, remote: true %></li>');
rating.append(element);

app/views/statistics/worst_close.js.erb
rating = $("#worst");
rating.empty();
<% @questions.each do |question| %>
element = $('<li><%= question.body %> (<%= question.question_worsts.count %>)</li>');
rating.append(element);
<% end %>
element = $('<li><%= link_to "Отобразить остальное", statistics_worst_display_path, remote: true %></li>');
rating.append(element);

app/views/statistics/worst_display.js.erb
rating = $("#worst");
rating.empty();
<% @questions.each do |question| %>
element = $('<li><%= question.body %> (<%= question.question_worsts.count %>)</li>');
rating.append(element);
<% end %>
element = $('<li><%= link_to "Свернуть", statistics_worst_close_path, remote: true %></li>');
rating.append(element);