config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root to: 'pages#main'

  get 'tournaments/:id/stat', to: 'tournaments#stat', as: 'tournament_stat'
  ActiveAdmin.routes(self)
  authenticate :user, lambda { |u| u.role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :themes, only: [:index, :show]
  resources :profiles
  resources :levels, only: [:show, :index]
  resources :posts, only: [:show, :index]
  resources :tournaments, only: [:show]
  resources :games, only: [:index, :show] do
    # collection do
    #   get ':id/rank', to: 'games#rank', as: 'rank'
    #   get ':id/play', to: 'user_games#play', as: 'play'
    #   get ':id/results', to: 'user_games#results', as: 'results'
    #   post ':id/begin_stage', to: 'user_games#begin_stage', as: 'begin_stage'
    #   post ':id/finish_stage', to: 'user_games#finish_stage', as: 'finish_stage'
    #   post ':game_id/save_statistic_anwers', to: 'user_games#save_statistic_anwers', as: 'user_game/save_statistic_anwers'
    # end
  end
  resources :user_games, only: [:create, :destroy] do
    resources :user_answers, only: [:create]
  end

  get 'games/:id/rank', to: 'games#rank', as: 'game_rank'
  get 'games/:id/play', to: 'user_games#play', as: 'user_game/play'
  get 'games/:id/results', to: 'user_games#results', as: 'user_game/results'
  post 'games/:id/begin_stage', to: 'user_games#begin_stage', as: 'user_game/begin_stage'
  post 'games/:id/finish_stage', to: 'user_games#finish_stage', as: 'user_game/finish_stage'
  post 'games/:game_id/save_statistic_anwers', to: 'user_games#save_statistic_anwers', as: 'user_game/save_statistic_anwers'

  namespace :statistics do
    get 'best_display'
    get 'best_close'
    get 'worst_display'
    get 'worst_close'
    get 'game_display'
    get 'game_close'
    get 'post_display'
    get 'post_close'
    get 'count_display'
    get 'count_close'
  end

  get 'callbacks/facebook'
  get 'search', to: 'pages#search'
  get 'pages/:url', to: 'pages#show', as: 'page'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    authenticated :user do
      root to: 'admin/dashboard#index', as: :authenticated_root
    end
    unauthenticated :user do
      root to: 'users/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/tournament.rb
class Tournament < ApplicationRecord
  has_many :games, dependent: :destroy
  has_many :achievements, dependent: :destroy

  mount_uploader :tournament_image, GameImageUploader
  
  def actual_game
    games.order(:start_time).each do |game|
      @result = game if game.start_time && Time.current < game.start_time + 4200
      break if @result
    end
    @result
  end

  def start_time
    self.actual_game.start_time
  end

  def results
    @results = []
    self.games.each do |game|
      game.user_games.each do |user_game|
        @results << {game: user_game.game.title, user: user_game.user.alias, score: user_game.total_score}
      end
    end
    @total = Hash.new(0)
    @results.each_with_object(@total) do |user|
      @total[user[:user]] += user[:score]
    end
    return @total
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  def show
    @tournament = Tournament.find(params[:id])
    render_404 unless @tournament.active
    @game = @tournament.actual_game
    @start_time = @game.start_time if @game
  end

  def stat
    @tournament = Tournament.last
    @results = @tournament.results
  end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/show.html.erb
<div class="row">
  <div class="col-xs-4 item-photo">
    <%= image_tag @tournament.tournament_image_url, style:"max-width:100%;" unless @tournament.tournament_image.blank? %>
  </div>
  <div class="col-xs-5" style="border:0px solid gray">
    <h3><%= @tournament.title %></h3>
    <h6><small>Стоимость регистрации на турнир: 0 сом</small></h6>
    <div style="padding-bottom:5px;">
      <%= @tournament.description %>
    </div>
    <h3 style="margin-top:0px;">Количество игр: <%= @tournament.games.count %></h3>
      <%= link_to "Зарегистрироваться на турнир", tournament_path(@tournament), class: "btn btn-success" %>
      <%= link_to "Статистика турнира", tournament_stat_path(@tournament), class: "btn btn-info" %>
  </div>
</div>
<br><br><br>

<div class="row">
<hr>
<%  if @game %>
  <div class="col-xs-2 item-photo">
    <%= image_tag @game.game_image_url, style:"max-width:100%;" if @game.game_image_url %>
  </div>
  <div class="col-xs-5" style="border:0px solid gray">
    <h3><%= @game.title   %></h3>
    <h6><small>Начало турнирной игры: <%= @game.start_time %></small></h6>
    <div style="padding-bottom:5px;">
      <%= @game.desc.html_safe %>
    </div>
    <div style="padding-bottom:5px;">
      Количество вопросов: <%= @game.questions.count %>
    </div>
    <div style="padding-bottom:5px;">
      Время на первый тур:  <%= @game.stage_time(1) %> мин.
    </div>
    <div style="padding-bottom:5px;">
      Время на второй тур:  <%= @game.stage_time(2) %> мин.
    </div>
    <div style="padding-bottom:5px;">
      Время на игру: <%= @game.stage_time([1,2]) %> мин.
    </div>
    <div class="section" style="padding-bottom:20px;">
      <%= link_to "Начать Игру", user_games_path(game: @game), method: :post, class: "btn btn-success" if Time.current >= @game.start_time%>
    </div>
      <% if @start_time %>
        <h3>Начнется через:</h3>
        <div id="CDT"></div>
      <% end %>
  </div>
  <% end %>
</div>

<div class="row statistic">
  <div>
    
  </div>
</div>
<br><br><br>

<script>
  function CountdownTimer(elm,tl,mes){
   this.initialize.apply(this,arguments);
 }
 CountdownTimer.prototype={
   initialize:function(elm,tl,mes) {
    this.elem = document.getElementById(elm);
    this.tl = tl;
    this.mes = mes;
  },countDown:function(){
    var timer='';
    var today=new Date();
    var day=Math.floor((this.tl-today)/(24*60*60*1000));
    var hour=Math.floor(((this.tl-today)%(24*60*60*1000))/(60*60*1000));
    var min=Math.floor(((this.tl-today)%(24*60*60*1000))/(60*1000))%60;
    var sec=Math.floor(((this.tl-today)%(24*60*60*1000))/1000)%60%60;
    var me=this;

    if( ( this.tl - today ) > 0 ){
     timer += '<span class="number-wrapper"><div class="line"></div><span class="caption">Дней: </span><span class="number day">'+day+'</span></span>';
     timer += '<span class="number-wrapper"><div class="line"></div><span class="caption">Часов: </span><span class="number hour">'+hour+'</span></span>';
     timer += '<span class="number-wrapper"><div class="line"></div><span class="caption">Минут: </span><span class="number min">'+this.addZero(min)+'</span></span><span class="number-wrapper"><div class="line"></div><span class="caption">Секунд: </span><span class="number sec">'+this.addZero(sec)+'</span></span>';
     this.elem.innerHTML = timer;
     tid = setTimeout( function(){me.countDown();},10 );
   }else{
     this.elem.innerHTML = this.mes;
     return;
   }
 },addZero:function(num){ return ('0'+num).slice(-2); }
}
function CDT(){

 // Set countdown limit
 var tl = new Date("<%= @start_time.year if @start_time %>/<%= @start_time.month if @start_time %>/<%= @start_time.day if @start_time %> <%= @start_time.hour if @start_time %>:<%= @start_time.min if @start_time %>:<%= @start_time.sec if @start_time %>");

 // You can add time's up message here
 var timer = new CountdownTimer('CDT',tl,'<span class="number-wrapper"><div class="line"></div><span class="number end">Время вышло!</span></span>');
 timer.countDown();
}
window.onload=function(){
 CDT();
}
</script>

app/views/tournaments/stat.html.erb
 <table class="table">
<caption>Общие результаты</caption>
  <% @results.each do |user, score| %>
  <tr>
    <td><%= user %></td>
    <td><%= score %></td
  </tr>    
  <% end %>
</table>

 <% @tournament.games.each do |game| %>
 <table class="table">
  <caption><%= game.title if game.user_games.any? %></caption>
  <% game.user_games.each do |user_game| %>
  <tr>
    <td><%= user_game.user.alias if user_game.total_score%></td>
    <td><%= user_game.total_score %></td>
  </tr>
  <% end %>
  </table>
<% end %>