config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root to: 'pages#main'

  get 'tournaments/:id/stat', to: 'tournaments#stat', as: 'tournament_stat'
  ActiveAdmin.routes(self)
  authenticate :user, lambda { |u| u.role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :themes, only: [:index, :show]
  resources :profiles
  resources :levels, only: [:show, :index]
  resources :posts, only: [:show, :index]
  resources :tournaments, only: [:show]
  resources :games, only: [:index, :show] do
    # collection do
    #   get ':id/rank', to: 'games#rank', as: 'rank'
    #   get ':id/play', to: 'user_games#play', as: 'play'
    #   get ':id/results', to: 'user_games#results', as: 'results'
    #   post ':id/begin_stage', to: 'user_games#begin_stage', as: 'begin_stage'
    #   post ':id/finish_stage', to: 'user_games#finish_stage', as: 'finish_stage'
    #   post ':game_id/save_statistic_anwers', to: 'user_games#save_statistic_anwers', as: 'user_game/save_statistic_anwers'
    # end
  end
  resources :user_games, only: [:create, :destroy] do
    resources :user_answers, only: [:create]
  end

  get 'games/:id/rank', to: 'games#rank', as: 'game_rank'
  get 'games/:id/play', to: 'user_games#play', as: 'user_game/play'
  get 'games/:id/results', to: 'user_games#results', as: 'user_game/results'
  post 'games/:id/begin_stage', to: 'user_games#begin_stage', as: 'user_game/begin_stage'
  post 'games/:id/finish_stage', to: 'user_games#finish_stage', as: 'user_game/finish_stage'
  post 'games/:game_id/save_statistic_anwers', to: 'user_games#save_statistic_anwers', as: 'user_game/save_statistic_anwers'

  namespace :statistics do
    get 'best_display'
    get 'best_close'
    get 'worst_display'
    get 'worst_close'
    get 'game_display'
    get 'game_close'
    get 'post_display'
    get 'post_close'
    get 'count_display'
    get 'count_close'
  end

  get 'callbacks/facebook'
  get 'search', to: 'pages#search'
  get 'pages/:url', to: 'pages#show', as: 'page'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    authenticated :user do
      root to: 'admin/dashboard#index', as: :authenticated_root
    end
    unauthenticated :user do
      root to: 'users/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/game.rb
class Game < ApplicationRecord
  include PgSearch
  paginates_per 10
  mount_uploader :game_image, GameImageUploader
  belongs_to :tournament
  has_many :questions, dependent: :nullify
  has_many :user_games, dependent: :destroy
  has_many :game_ratings, dependent: :destroy
  belongs_to :level
  belongs_to :theme
  validates :title, presence: true
  validates :desc, presence: true
  validates :theme, presence: true

  pg_search_scope :search_for, against: %i(title desc),
                  using: { tsearch: { any_word: true },
                           trigram: { threshold: 0.1 }}


  def time_to_start
    time = self.start_time - Time.current
    Time.at(time).utc.strftime('%m месяцев %d дней %H часов %M минут')
  end

  def is_tournament_game?
    tournament != nil
  end

  def stage_time(stage)
    questions.where(stage: stage).count * 3
  end

  def rating
    game_ratings.length > 0 ? game_ratings.average(:rating).to_f : 0.0
  end

  def self.sort_array_by_rating
    Game.all.select{ |game| game.rating > 0 }.sort_by(&:rating).reverse
  end

  def self.game_sort
    games = Game.all.select{ |game| game.user_games.count != 0 }
    games.sort_by{ |game| game.user_games.count }.reverse
  end

  def random_results
    all.shuffle.take(3)
  end

  def self.best
    Game.all.sort_by(&:rating).reverse.first(3)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  	@games = Game.where(active: true).order(title: :ASC).page params[:page]
  end

  def show
    @game = Game.find(params[:id])
  end

  def rank
    @game = Game.find(params[:id])

    @first_results = []
    uniq_ids = []
    @game.user_games.order("created_at ASC").each do |user_game|
      unless uniq_ids.include? user_game.user.id
        if user_game.user.alias != "guest" && user_game.stage2_finish_time != nil
          @first_results << user_game
          uniq_ids << user_game.user.id
        end
      end
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_games_table.html.erb
<div class="table-responsive" style="background-color: lightblue; border-radius: 10px;">
  <table class="table" id="games">
    <thead>
    <tr>
      <th>Название игры</th>
      <th>Описание игры</th>
      <th>Уровень</th>
      <th>Тематика</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% games.each do |game| %>
        <tr>
          <td class="active"><%= link_to game.title, game_path(game), style: "color: #0066cc" %></td>
          <td class="active"><%= game.desc %></td>
          <td class="active"><%= game.level.name if game.level %></td>
          <td class="active"><%= game.theme.name if game.theme %></td>
          <td class="active"><%= image_tag game.game_image, height: '50' if game.game_image %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

</div>

<%= paginate games %>

app/views/games/index.html.erb
<%= render 'games/games_table', games: @games %>

app/views/games/rank.html.erb
<table class="table table-hover" id="ranks">
  <thead>
    <tr>
      <th>Игра</th>
      <th>Игрок</th>
      <th>Результат</th>
      <th>Время, сек</th>
    </tr>
  </thead>
  <tbody>
    <% @first_results.each do |user_game| %>
      <tr>
        <td><%= user_game.game.title %></td>
        <td><%= user_game.registered %></td>
        <td><%= user_game.total_score %></td>
        <td><%= user_game.total_time.round(2) if user_game.total_time %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/show.html.erb
<div class="row">
  <div class="col-xs-4 item-photo">
    <%= image_tag @game.game_image_url, style:"max-width:100%;" unless @game.game_image.blank? %>
  </div>
  <div class="col-xs-5" style="border:0px solid gray">
    <h3><%= @game.title %></h3>
    <h6><small><%= @game.theme.name if @game.theme %></small></h6>
    <% if current_user && current_user.role?(:admin) %>
      <h6><small>Рейтинг игры: <%= @game.rating %></small></h6>
    <% end %>
    <div style="padding-bottom:5px;">
        <%= @game.desc %>
    </div>
    <div style="padding-bottom:5px;">
      Количество вопросов: <%= @game.questions.count %>
    </div>
    <div style="padding-bottom:5px;">
      Время на первый тур:  <%= @game.stage_time(1) %> мин.
    </div>
    <div style="padding-bottom:5px;">
      Время на второй тур:  <%= @game.stage_time(2) %> мин.
    </div>
    <div style="padding-bottom:5px;">
      Время на игру: <%= @game.stage_time([1,2]) %> мин.
    </div>
    <h3 style="margin-top:0px;">0 сом</h3>
    <div class="section" style="padding-bottom:20px;">
      <% if current_or_guest_user.not_finished_game %>
        <%= render 'layouts/return_to_game_button' %>
      <% else %>
        <%= link_to "Начать Игру", user_games_path(game: @game), method: :post, class: "btn btn-success" %>
      <% end %>

      <%= link_to "Статистика", game_rank_path(@game), class: "btn btn-info" %>
    </div>
  </div>
</div>