config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root to: 'pages#main'

  get 'tournaments/:id/stat', to: 'tournaments#stat', as: 'tournament_stat'
  ActiveAdmin.routes(self)
  authenticate :user, lambda { |u| u.role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :themes, only: [:index, :show]
  resources :profiles
  resources :levels, only: [:show, :index]
  resources :posts, only: [:show, :index]
  resources :tournaments, only: [:show]
  resources :games, only: [:index, :show] do
    # collection do
    #   get ':id/rank', to: 'games#rank', as: 'rank'
    #   get ':id/play', to: 'user_games#play', as: 'play'
    #   get ':id/results', to: 'user_games#results', as: 'results'
    #   post ':id/begin_stage', to: 'user_games#begin_stage', as: 'begin_stage'
    #   post ':id/finish_stage', to: 'user_games#finish_stage', as: 'finish_stage'
    #   post ':game_id/save_statistic_anwers', to: 'user_games#save_statistic_anwers', as: 'user_game/save_statistic_anwers'
    # end
  end
  resources :user_games, only: [:create, :destroy] do
    resources :user_answers, only: [:create]
  end

  get 'games/:id/rank', to: 'games#rank', as: 'game_rank'
  get 'games/:id/play', to: 'user_games#play', as: 'user_game/play'
  get 'games/:id/results', to: 'user_games#results', as: 'user_game/results'
  post 'games/:id/begin_stage', to: 'user_games#begin_stage', as: 'user_game/begin_stage'
  post 'games/:id/finish_stage', to: 'user_games#finish_stage', as: 'user_game/finish_stage'
  post 'games/:game_id/save_statistic_anwers', to: 'user_games#save_statistic_anwers', as: 'user_game/save_statistic_anwers'

  namespace :statistics do
    get 'best_display'
    get 'best_close'
    get 'worst_display'
    get 'worst_close'
    get 'game_display'
    get 'game_close'
    get 'post_display'
    get 'post_close'
    get 'count_display'
    get 'count_close'
  end

  get 'callbacks/facebook'
  get 'search', to: 'pages#search'
  get 'pages/:url', to: 'pages#show', as: 'page'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    authenticated :user do
      root to: 'admin/dashboard#index', as: :authenticated_root
    end
    unauthenticated :user do
      root to: 'users/sessions#new', as: :unauthenticated_root
    end
  end

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="nav navbar-nav navbar-left">
        <li><%= image_tag "logo_2.png", style: "max-height: 40px; padding: 15px 10px 0 0;", id: 'logo' %></li>
      </div>
    <div class="navbar-header">
      <%= link_to 'Московские Классики', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= form_tag search_path, method: :get, class: 'navbar-form navbar-left', id: 'search_form' do |f| %>
          <%= text_field_tag :search, params[:search], type: 'text', class: 'form-control', placeholder: 'Поиск' %>
          <%= submit_tag "Найти", type: 'submit', class: 'btn btn-default', name: nil %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">

        <% if current_or_guest_user == guest_user %>
            <li class="navbar-text">Привет, Гость!</li>
        <% end %>
        <li><%= link_to 'Тематики', themes_path %></li>
        <li><%= link_to 'Все игры', games_path %></li>
        <% if signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="login_dropdown" role="button" aria-haspopup="true" aria-expanded="false">Аккаунт <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to ("Личный кабинет"), profile_path(current_user.id) %></li>
                <li><%= link_to "Изменить данные", edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to (t 'navbar.sign_out'), destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>

            <li><%= link_to "Панель управления", admin_root_path if current_user.role?(:admin) %></li>
      <% else %>
            <li><%= link_to (t 'navbar.sign_up'), new_user_registration_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Войти <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "#{image_tag("f.png", size: "20x20")} Facebook".html_safe, user_facebook_omniauth_authorize_path %></li>
                <li><%= link_to "#{image_tag("g.png", size: "20x20")} Google".html_safe, user_google_oauth2_omniauth_authorize_path %></li>
                <li><%= link_to "#{image_tag("v.png", size: "20x20")} Vk".html_safe, user_vkontakte_omniauth_authorize_path %></li>
                <li role="separator" class="divider"></li>
                <li id="login"><%= link_to "Обычный вход", new_user_session_path %></li>
              </ul>
            </li>
        <% end %>
      </ul><!-- /.login toolbar -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_return_to_game_button.html.erb
<% if current_or_guest_user.not_finished_game.stage1_finish_time && current_or_guest_user.not_finished_game.stage2_start_time.blank? %>
  <%= link_to "Вернуться в игру '#{current_or_guest_user.not_finished_game.game.title}'", user_game_results_path(current_or_guest_user.not_finished_game), class: 'btn btn-warning' %>
<% else %>
  <%= link_to "Вернуться в игру '#{current_or_guest_user.not_finished_game.game.title}'", user_game_play_path(current_or_guest_user.not_finished_game), class: 'btn btn-warning' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Klassiki</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/navbar' %>
  <div class="container">
    <p><%= notice %></p>
    <p><%= alert %></p>
    <%= yield %>
  </div>
</body>
</html>